version: "3.7"

services:

  mysql:
    build:
      context: mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: r0o0ot
    volumes:
      - lamp_mysql:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - backend
    volumes:
      - ./public:/app
    depends_on:
      - mysql

  apache:
    build:
      context: .
      dockerfile: apache/Dockerfile
    ports:
      - "6666:80"
    networks:
      - frontend
      - backend
    volumes:
      - ./public:/usr/local/apache2/htdocs
    depends_on:
      - php
      - mysql


networks:
  frontend:
    name: frontend
  backend:
    name: backend
volumes:
  lamp_mysql:
    name: lamp_mysql
